/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristobal
 */
public class comunas extends javax.swing.JFrame {

    conectar cn=new conectar();
    DefaultListModel modeloComunas=new DefaultListModel();
    DefaultListModel modeloFerias=new DefaultListModel();
    DefaultListModel modeloProductos= new DefaultListModel();
    public comunas() {
        initComponents();
        ListaComunas.setModel(modeloComunas);
        ListaFerias.setModel(modeloFerias);
        ListaProductos.setModel(modeloProductos);
        mostrarDatos();
    }
            
    private void mostrarDatos(){
        
        String SQL="SELECT * FROM comunas ORDER BY nombre_comuna";
        String datos[]=new String[1];   
        
        try {
            cn.conexion();
            cn.st=cn.conec.createStatement();
            cn.rt=cn.st.executeQuery(SQL);
            while (cn.rt.next()) {
                datos[0]=cn.rt.getString(2);
                modeloComunas.addElement(datos[0]);
                
            }
        } catch (Exception e) {
           // JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaComunas = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaFerias = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListaProductos = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ListaComunas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListaComunas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListaComunasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ListaComunas);

        ListaFerias.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListaFerias.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListaFeriasValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(ListaFerias);

        ListaProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(ListaProductos);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Comunas");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Ferias");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Productos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(127, 127, 127)
                .addComponent(jLabel3)
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListaComunasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListaComunasValueChanged
        modeloFerias.clear();
        String comuna=ListaComunas.getSelectedValue();
        if (comuna.length() > 0){
        String SQL="select nombre_feria from ferias f inner join  comunas c on c.id_comuna = f.id_comuna where  c.nombre_comuna='"+comuna+"';";
        try{
           cn.conexion();
           cn.st=cn.conec.createStatement();
           cn.rt=cn.st.executeQuery(SQL);
           while (cn.rt.next()){
               
                modeloFerias.addElement(cn.rt.getString(1));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        } 
        
    }//GEN-LAST:event_ListaComunasValueChanged

    private void ListaFeriasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListaFeriasValueChanged
        modeloProductos.clear();
        String feria=ListaFerias.getSelectedValue();
        if (feria.length() > 0){
        String SQL="select  nombre, precio, puesto from ferias f inner join  productos p on p.id_feria = f.id_feria where  f.nombre_feria='"+feria+"';";
        try{
           cn.conexion();
           cn.st=cn.conec.createStatement();
           cn.rt=cn.st.executeQuery(SQL);
           String line_product = null;
           line_product = formateo_string_producto(cn);
           modeloProductos.addElement(line_product);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        } 
    }//GEN-LAST:event_ListaFeriasValueChanged
    public String formateo_string_producto(conectar con) throws SQLException{
        /**
         * @param con objeto de coneccion para formatear el resultado de la query
         */
        String formated_string = null ;
        while(con.rt.next()){
            formated_string = con.rt.getString(1) + ' ' + con.rt.getString(2) + ' ' + con.rt.getString(3);
        }
        return formated_string;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(comunas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(comunas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(comunas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(comunas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new comunas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListaComunas;
    private javax.swing.JList<String> ListaFerias;
    private javax.swing.JList<String> ListaProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
